DoctorsApp/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CORE.CODE;
using CORE.DATAMODEL;
using CORE.DATAMODEL.Payment;

namespace DoctorsApp.Controllers
{
    public class CheckoutController : Controller
    {
        #region Global Variable
        private readonly IPaymentStrategy _payments;
        private readonly IGlobal _global;
        #endregion
        #region CTOR
        public CheckoutController(IPaymentStrategy payments, IGlobal global)
        {
            _payments = payments;
            _global = global;
        }
        #endregion
        // GET: Checkout
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Confirm()
        {
            IPayment payment = _payments.GetPayment(_global.GetAllConfigs().FirstOrDefault(x=>x.Key== "PaymentClass").Value);
            AuthoriseRequest authoriseRequest = new AuthoriseRequest()
            {
                
            };
            var response=payment.Authorise(authoriseRequest);

            return View();
        }
    }
}

DoctorsApp/Controllers/DoctorController.cs
using CORE.CODE;
using CORE.DATAMODEL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctorsApp.Controllers
{
    public class DoctorController : Controller
    {
        #region Global Variable
        private readonly IDoctorRegistrationServices _RS;
        #endregion
        #region CTOR
        public DoctorController(IDoctorRegistrationServices RS)
        {
            _RS = RS;
        }
        #endregion
        // GET: Doctor
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateDoctorProfile()
        {
            DoctorInsertModel model = new DoctorInsertModel();
            model.DoctorTypeList = _RS.GetDoctorTypes().ToList();
            return View(model);
        }
        [HttpPost]
        public ActionResult CreateDoctorProfile(DoctorInsertModel model,HttpPostedFileBase File)
        {
            model.DoctorTypeList = _RS.GetDoctorTypes().ToList();
            if (!ModelState.IsValid)
            {
                TempData["Message"] = "Verification failed";
                TempData["IsError"] = "true";
            }

            TempData["Message"] = "Verification failed";
            TempData["IsError"] = "true";
            return View(model);
        }

    }
}

DoctorsApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctorsApp.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

DoctorsApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CORE.DATAMODEL;

namespace DoctorsApp.Controllers
{
    /// <summary>
    /// Login Controller
    /// </summary>
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(LoginRequest loginRequest)
        {
            return View();
        }
    }
}

DoctorsApp/Controllers/RegisterController.cs
using CORE.CODE;
using CORE.CODE.Registration.Doctor;
using CORE.DATAMODEL.Doctor;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctorsApp.Controllers
{
    public class RegisterController : Controller
    {
        #region Global Variables
        ICommonServices _commonServices;
        IDoctorServices _doctorServices;
        #endregion

        #region CTOR
        public RegisterController(ICommonServices commonServices,IDoctorServices doctorServices)
        {
            _commonServices = commonServices;
            _doctorServices = doctorServices;
        }
        #endregion

        // GET: Register
        public ActionResult Index()
        {
            DoctorRegistration doctorRegistration = new DoctorRegistration();
            doctorRegistration.states = _commonServices.GetStates().ToList();
            doctorRegistration.specializations = _commonServices.GetSpecializations().ToList();
            doctorRegistration.cities = new List<CORE.DATAMODEL.Common.City>();
            return View(doctorRegistration);
        }

        [HttpPost]
        public ActionResult Index(DoctorRegistration req)
        {
            if (!ModelState.IsValid)
            {
                req.states = _commonServices.GetStates().ToList();
                req.specializations = _commonServices.GetSpecializations().ToList();
                req.cities = _commonServices.GetCities(req.State).ToList();
                return View(req);
            }
            else
            {
                return RedirectToAction("Index", "Dashboard",new { });
            }
        }

       
        [HttpGet]
        public JsonResult GetCities(string StateCode)
        {
            List<CORE.DATAMODEL.Common.City> cities = new List<CORE.DATAMODEL.Common.City>();
            try
            {
                cities = _commonServices.GetCities(StateCode).ToList();
            }
            catch(Exception ex) { }
            return Json(cities, JsonRequestBehavior.AllowGet);
        }
    }
}

DoctorsApp/Views/Login/Index.cshtml
@model CORE.DATAMODEL.LoginRequest

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

<div class="container body-content wrapper fadeInDown">
    <div id="formContent">

        @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { htmlAttributes = new { @autocomplete = "off" }, @id = "frmLogin" }))
        {
            <div class="form-horizontal">
                <div class="fadeIn first">
                    <i class="fa fa-user-circle" id="icon" aria-hidden="true"></i>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-12" })
                    <div class="col-md-12">
                        <div class="">
                            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="">
                            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-12" })
                    <div class="col-md-12">
                        <div class="">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                        </div>
                        <div class="">
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        @Html.CheckBoxFor(model => model.Rememberme) <span>Remember me</span>
                    </div>
                    <div class="col-md-6" style="float:left">
                        @Html.ActionLink("Register Here", "Index", "Register")
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <input type="submit" value="Login" class="active" />
                    </div>
                    <div class="col-md-6">
                        @Html.ActionLink("Forgot Password?", "ForgotPassword", "Login")
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<!--CSS-->

<link href="~/Scripts/css/Login/Style.css" rel="stylesheet" />

DoctorsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    @*<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>*@
    @*<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">*@
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>*@

    <div class="nothing">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Doctor's point</p>
        </footer>
    </div>
</body>
</html>